# Generated by Django 2.1 on 2018-11-11 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type', models.CharField(choices=[('Processor', 'Processor'), ('CPU Cooler', 'CPU Cooler'), ('Motherboard', 'Motherboard'), ('Memory', 'Memory'), ('Storage', 'Storage'), ('GPU', 'GPU'), ('Case', 'Case'), ('PSU', 'PSU'), ('OS', 'OS'), ('Monitor', 'Monitor')], max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='parts',
            field=models.ManyToManyField(blank=True, to='pc_build.Part'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
