# Generated by Django 2.1 on 2018-11-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_build', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='currency',
            field=models.CharField(default='₹', max_length=10),
        ),
    ]
