# Generated by Django 2.1 on 2018-11-11 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pc_build', '0002_part_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='parts',
        ),
        migrations.AddField(
            model_name='cart',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case', to='pc_build.Part'),
        ),
        migrations.AddField(
            model_name='cart',
            name='cpu_cooler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpu_cooler', to='pc_build.Part'),
        ),
        migrations.AddField(
            model_name='cart',
            name='gpu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gpu', to='pc_build.Part'),
        ),
        migrations.AddField(
            model_name='cart',
            name='memory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='pc_build.Part'),
        ),
        migrations.AddField(
            model_name='cart',
            name='monitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor', to='pc_build.Part'),
        ),
        migrations.AddField(
            model_name='cart',
            name='motherboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motherboard', to='pc_build.Part'),
        ),
        migrations.AddField(
            model_name='cart',
            name='os',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='os', to='pc_build.Part'),
        ),
        migrations.AddField(
            model_name='cart',
            name='processor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processor', to='pc_build.Part'),
        ),
        migrations.AddField(
            model_name='cart',
            name='psu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psu', to='pc_build.Part'),
        ),
        migrations.AddField(
            model_name='cart',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='pc_build.Part'),
        ),
    ]
