# Generated by Django 2.1 on 2018-11-11 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pc_build', '0003_auto_20181111_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cpu_cooler',
            field=models.ForeignKey(limit_choices_to={'part_type': 'CPU Cooler'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpu_cooler', to='pc_build.Part'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='processor',
            field=models.ForeignKey(limit_choices_to={'part_type': 'Processor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processor', to='pc_build.Part'),
        ),
    ]
