# Generated by Django 2.1 on 2018-11-11 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pc_build', '0004_auto_20181111_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='case',
            field=models.ForeignKey(limit_choices_to={'part_type': 'Case'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case', to='pc_build.Part'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='gpu',
            field=models.ForeignKey(limit_choices_to={'part_type': 'GPU'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gpu', to='pc_build.Part'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='memory',
            field=models.ForeignKey(limit_choices_to={'part_type': 'Memory'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='pc_build.Part'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='monitor',
            field=models.ForeignKey(limit_choices_to={'part_type': 'Monitor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor', to='pc_build.Part'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='motherboard',
            field=models.ForeignKey(limit_choices_to={'part_type': 'Motherboard'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motherboard', to='pc_build.Part'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='os',
            field=models.ForeignKey(limit_choices_to={'part_type': 'OS'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='os', to='pc_build.Part'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='psu',
            field=models.ForeignKey(limit_choices_to={'part_type': 'PSU'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psu', to='pc_build.Part'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='storage',
            field=models.ForeignKey(limit_choices_to={'part_type': 'Storage'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='pc_build.Part'),
        ),
    ]
