# Generated by Django 2.1 on 2018-11-11 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pc_build', '0005_auto_20181111_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='case',
            field=models.ForeignKey(blank=True, limit_choices_to={'part_type': 'Case'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case', to='pc_build.Part'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cpu_cooler',
            field=models.ForeignKey(blank=True, limit_choices_to={'part_type': 'CPU Cooler'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpu_cooler', to='pc_build.Part'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='gpu',
            field=models.ForeignKey(blank=True, limit_choices_to={'part_type': 'GPU'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gpu', to='pc_build.Part'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='memory',
            field=models.ForeignKey(blank=True, limit_choices_to={'part_type': 'Memory'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='pc_build.Part'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='monitor',
            field=models.ForeignKey(blank=True, limit_choices_to={'part_type': 'Monitor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor', to='pc_build.Part'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='motherboard',
            field=models.ForeignKey(blank=True, limit_choices_to={'part_type': 'Motherboard'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motherboard', to='pc_build.Part'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='os',
            field=models.ForeignKey(blank=True, limit_choices_to={'part_type': 'OS'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='os', to='pc_build.Part'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='processor',
            field=models.ForeignKey(blank=True, limit_choices_to={'part_type': 'Processor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processor', to='pc_build.Part'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='psu',
            field=models.ForeignKey(blank=True, limit_choices_to={'part_type': 'PSU'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psu', to='pc_build.Part'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='storage',
            field=models.ForeignKey(blank=True, limit_choices_to={'part_type': 'Storage'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='pc_build.Part'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_type',
            field=models.CharField(choices=[('processor', 'Processor'), ('cpu_cooler', 'CPU Cooler'), ('motherboard', 'Motherboard'), ('memory', 'Memory'), ('storage', 'Storage'), ('gpu', 'GPU'), ('case', 'Case'), ('psu', 'PSU'), ('os', 'OS'), ('monitor', 'Monitor')], max_length=1000),
        ),
    ]
