# Generated by Django 2.1 on 2018-11-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_build', '0006_auto_20181111_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_type',
            field=models.CharField(choices=[('Processor', 'Processor'), ('CPU Cooler', 'CPU Cooler'), ('Motherboard', 'Motherboard'), ('Memory', 'Memory'), ('Storage', 'Storage'), ('GPU', 'GPU'), ('Case', 'Case'), ('PSU', 'PSU'), ('OS', 'OS'), ('Monitor', 'Monitor')], max_length=1000),
        ),
    ]
