# Generated by Django 2.1 on 2018-11-11 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pc_build', '0012_order_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='time',
            new_name='date_time',
        ),
    ]
